### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MattTwinkleToes** [laconicwolf/Nmap-Scan-to-CSV#3]
I'm not great with python but I just tried to run your script (thanks for posting it) and encountered this issue straight away

`$ python nmap_xml_parser.py -f nmap_ping_scan_080219.xml 
  File "nmap_xml_parser.py", line 7
    <!DOCTYPE html>
    ^
`
It seems to be looking for an html file?

**Comment by laconicwolf** [comment]
Thanks, and sorry for the delay...didn't see this. I just verified the script works with Nmap 7.70 on Windows 10 home and with Nmap 7.40 on Debian Stretch using Python 3.7. Should work with earlier version as far as I know. Any chance you can upload your xml file, or let me know the Nmap command used to generate the output file? Maybe the type of scan produced a use case that I didn't plan on. Thanks again.

**Comment by Theory5** [comment]
@laconicwolf I'm having the same problem!

I'm not OP, and I cannot provide you with my output either because it contains sensitive info. I can tell you that this is my version and os:

Linux  4.4.0-31-generic x86_64 Ubuntu

Ubuntu 16.04.6 LTS

Nmap version 7.01 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.2.4 openssl-1.0.2g libpcre-8.38 libpcap-1.7.4 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

I used the python3 command as in your documentation, and this was the error output:

`  File "nmap_xml_parser.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax`

Does this help you at all? If not, I can get a test output xml that doesn't have sensitive data and upload it if OP doesn't get back to you by the time you're responding to me! Thanks for taking a look and it should be very helpful for me once we get this running. 

EDIT: Sorry, trying to figure out how to show the exact spacing... github seems to not like carriage returns in the code tags. The ^ is pointing to the first `<` in `<!DOCTYPE html>` if that helps.

**Comment by Theory5** [comment]
Well a brief look at the "script" I pulled down shows how much I know. I didn't get the script, I pulled the entire page from github! d'oh! @MattTwinkleToes ensure you wget the script, not the webpage like I did, which is why we're getting that HTML doctype error. 


Look here: 

https://stackoverflow.com/questions/37818409/strange-html-doctype-error-when-trying-to-run-python-script-from-bash

**Comment by MattTwinkleToes** [comment]
> Thanks, and sorry for the delay...didn't see this. I just verified the script works with Nmap 7.70 on Windows 10 home and with Nmap 7.40 on Debian Stretch using Python 3.7. Should work with earlier version as far as I know. Any chance you can upload your xml file, or let me know the Nmap command used to generate the output file? Maybe the type of scan produced a use case that I didn't plan on. Thanks again.


Can I send you the .xml privately?  I'm not keen on uploading all of that data into a public page.

I used this to create the xml

`sudo nmap -sP 192.168.1.0/24 -oX nmap_ping_scan_260219.xml
`

**Comment by MattTwinkleToes** [comment]
> Well a brief look at the "script" I pulled down shows how much I know. I didn't get the script, I pulled the entire page from github! d'oh! @MattTwinkleToes ensure you wget the script, not the webpage like I did, which is why we're getting that HTML doctype error.
> 
> Look here:
> 
> https://stackoverflow.com/questions/37818409/strange-html-doctype-error-when-trying-to-run-python-script-from-bash

Glad you found a solution for you, this is not the same issue as me.  I git-cloned the script and can execute it.

**Comment by laconicwolf** [comment]
@MattTwinkleToes I sent you an email.

**Comment by laconicwolf** [comment]
Closing. Never heard back and haven't heard of any similar issue.
